name = "code-tic"          # nome do Worker
type = "javascript"           # ou "typescript" se for TS
account_id = "d1981790c750476d614abdf6ea6f428d" # pegue na sua conta Cloudflare
workers_dev = true
compatibility_date = "2025-09-22"

# Configuração para servir arquivos estáticos
[site]
bucket = "./"  # pasta onde estão os HTML, CSS, JS
entry-point = "workers-site"    
